# Site settings
# ─────────────
# Edit these values. They’re used throughout index.html via Liquid variables.

title: "Walid Hasan"
description: "Incoming graduate student at University of Manitoba"
email: "hasanw [at] myumanitoba [dot] ca"
url: "https://hasan-walid.github.io"  # update after you create the repo
baseurl: ""

# Buttons/links under your bio
cv_url: "/files/CV_july_2026.pdf"
socials:
  - { name: "linkedin",       url: "https://www.linkedin.com/in/walid-hasan/" }
  - { name: "github",         url: "https://github.com/hasan-walid" }
  - { name: "facebook",       url: "https://www.facebook.com/suprov.81" }
  - { name: "substack",       url: "https://muktobihongo.substack.com/"}

# Jekyll settings (GitHub Pages will build this automatically)
markdown: kramdown
plugins:
  - jekyll-seo-tag
# theme: null  # we’re using custom HTML/CSS

# Optional SEO author block
author:
  name: "Walid Hasan"
  url: "https://hasan-walid.github.io"
