# Site settings
# ─────────────
# Edit these values. They’re used throughout index.html via Liquid variables.

title: "Walid Hasan"
description: "Senior Physics Undergrad at Brac University."
email: "walidsuprov@gmail.com"  # change to your email
url: "https://hasan-walid.github.io"  # update after you create the repo
baseurl: ""

# Buttons/links under your bio
cv_url: "/files/CV.pdf"
socials:
  - { name: "LinkedIn", url: "https://www.linkedin.com/in/walid-hasan/" }
  - { name: "Facebook", url: "https://www.facebook.com/suprov.81" }
  - { name: "GitHub", url: "https://github.com/hasan-walid" }
  - { name: "Substack", url: "https://muktobihongo.substack.com/" }


# Jekyll settings (GitHub Pages will build this automatically)
markdown: kramdown
plugins:
  - jekyll-seo-tag
# theme: null  # we’re using custom HTML/CSS

# Optional SEO author block
author:
  name: "Walid Hasan"
  url: "https://hasan-walid.github.io"
